/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cc.ui;

import com.alex.store.Store;
import com.cc.Main;
import com.cc.tools.ItemPack;
import static com.cc.tools.ItemPack.utilizeSettings;
import com.cc.tools.Utils;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author travis
 */
public class ItemUI extends javax.swing.JFrame {
    
    /**
     * Creates new form ItemUI
     */
    public ItemUI() {
        setTitle("Custom Item Packing - Somethin Catchy");
        setResizable(false);
        redirectSystemStreams();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backToMainButton = new javax.swing.JButton();
        packButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        itemID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        itemName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        itemValue = new javax.swing.JTextField();
        membersOnly = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        equipSlot = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        equipType = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        copyItemID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        notedItemID = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        inv0 = new javax.swing.JTextField();
        inv1 = new javax.swing.JTextField();
        inv2 = new javax.swing.JTextField();
        inv3 = new javax.swing.JTextField();
        inv4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ground0 = new javax.swing.JTextField();
        ground1 = new javax.swing.JTextField();
        ground2 = new javax.swing.JTextField();
        ground3 = new javax.swing.JTextField();
        ground4 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        invModel = new javax.swing.JTextField();
        invModelButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        invModelZoom = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        maleEquip2 = new javax.swing.JTextField();
        maleEquip2Button = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        femaleEquip2 = new javax.swing.JTextField();
        femaleEquip2Button = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        maleEquip3 = new javax.swing.JTextField();
        maleEquip3Button = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        femaleEquip3 = new javax.swing.JTextField();
        femaleEquip3Button = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        maleEquip1 = new javax.swing.JTextField();
        maleEquip1Button = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        femaleEquip1 = new javax.swing.JTextField();
        femaleEquip1Button = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        teamID = new javax.swing.JTextField();
        stackable = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        stackIDs = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        stackAmts = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lendItemID = new javax.swing.JTextField();
        switchLendItemID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        changedModelColors = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        changedTextureColors = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        weaponType = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        renderAnimation = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        modelOffset1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        modelOffset2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        modelRotation1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        modelRotation2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cc/ui/customitempacking.png"))); // NOI18N

        backToMainButton.setText("Back To Main UI");
        backToMainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainButtonActionPerformed(evt);
            }
        });

        packButton.setText("Pack Item");
        packButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("New Item ID");

        itemID.setText("-1");
        itemID.setToolTipText("Enter the item's ID you wish to create.");
        itemID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                itemIDKeyTyped(evt);
            }
        });

        jLabel3.setText("New Item Name");

        itemName.setText("null");
        itemName.setToolTipText("Enter your new Item's Name.");

        jLabel4.setText("New Item Value");

        itemValue.setText("0");
        itemValue.setToolTipText("Enter the item's value in GP.");
        itemValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                itemValueKeyTyped(evt);
            }
        });

        membersOnly.setText("Members Only");
        membersOnly.setToolTipText("Check this box to make the item a members only item.");

        jLabel5.setText("Equip Slot");

        equipSlot.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hat", "Cape", "Amulet", "Weapon", "Chest", "Shield", "Legs", "Hands", "Feet", "Ring", "Arrows", "Aura" }));
        equipSlot.setToolTipText("Select where your item Equips, if it equips.");

        jLabel6.setText("Equip Type");

        equipType.setText("-1");
        equipType.setToolTipText("<html>\n<p>Two Handed Weapons Enter \"5\"\n<br />\nChest Item That Hides Arms Enter \"6\"\n<br />\nHelmet Item That Hides Hair Enter \"8\"\n</p>\n</html>");
        equipType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                equipTypeKeyTyped(evt);
            }
        });

        jLabel7.setText("Copied Item ID");

        copyItemID.setText("0");
        copyItemID.setToolTipText("<html>\n<p>\nEnter the Item You'd like to have fill in the spaces you don't enter.\n<br />\nCan be used to create colored Items. E.G. Black Party Hats.\n<br />\nIf not copying an item, leave as 0.\n</p>\n</html>");
        copyItemID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                copyItemIDKeyTyped(evt);
            }
        });

        jLabel13.setText("Noted Item ID");

        notedItemID.setText("-1");
        notedItemID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                notedItemIDKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(itemID, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(itemValue, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(notedItemID, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(equipType, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(equipSlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(copyItemID, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(membersOnly))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equipSlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equipType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(copyItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(membersOnly))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notedItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Basic Options", jPanel1);

        jLabel8.setText("Inventory Options");

        inv0.setText(null);
        inv0.setToolTipText("First Inventory Option");

        inv1.setText("Wear");
        inv1.setToolTipText("Second Inventory Option");

        inv2.setText(null);
        inv2.setToolTipText("Third Inventory Option");

        inv3.setText(null);
        inv3.setToolTipText("Fourth Inventory Option");

        inv4.setText("Drop");
        inv4.setToolTipText("Fifth Inventory Option");

        jLabel9.setText("Ground Options");

        ground0.setText(null);
        ground0.setToolTipText("First Ground Option");

        ground1.setText(null);
        ground1.setToolTipText("Second Ground Option");

        ground2.setText("Take");
        ground2.setToolTipText("Third Ground Option");

        ground3.setText(null);
        ground3.setToolTipText("Fourth Ground Option");

        ground4.setText(null);
        ground4.setToolTipText("Fifth Ground Option");

        jLabel29.setText("When leaving an option blank, please type \"null\" in the place.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ground0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(inv0, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(inv1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inv2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ground1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ground2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inv3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(ground3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inv4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(ground4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel29)))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inv0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inv4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ground0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ground2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ground3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ground4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jLabel29)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Right Click Options", jPanel2);

        jLabel16.setText("Inventory Model");

        invModel.setText("-1");
        invModel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                invModelKeyTyped(evt);
            }
        });

        invModelButton.setText("Browse");
        invModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invModelButtonActionPerformed(evt);
            }
        });

        jLabel17.setText("Inventory Model Zoom");

        invModelZoom.setText("2000");
        invModelZoom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                invModelZoomKeyTyped(evt);
            }
        });

        jLabel18.setText("Male Model Equip 2");

        maleEquip2.setText("-1");
        maleEquip2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maleEquip2KeyTyped(evt);
            }
        });

        maleEquip2Button.setText("Browse");
        maleEquip2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleEquip2ButtonActionPerformed(evt);
            }
        });

        jLabel19.setText("Female Model Equip 2");

        femaleEquip2.setText("-1");
        femaleEquip2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                femaleEquip2KeyTyped(evt);
            }
        });

        femaleEquip2Button.setText("Browse");
        femaleEquip2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleEquip2ButtonActionPerformed(evt);
            }
        });

        jLabel20.setText("Male Model Equip 3");

        maleEquip3.setText("-1");
        maleEquip3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maleEquip3KeyTyped(evt);
            }
        });

        maleEquip3Button.setText("Browse");
        maleEquip3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleEquip3ButtonActionPerformed(evt);
            }
        });

        jLabel21.setText("Female Model Equip 3");

        femaleEquip3.setText("-1");
        femaleEquip3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                femaleEquip3KeyTyped(evt);
            }
        });

        femaleEquip3Button.setText("Browse");
        femaleEquip3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleEquip3ButtonActionPerformed(evt);
            }
        });

        jLabel23.setText("Male Model Equip 1");

        maleEquip1.setText("-1");
        maleEquip1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maleEquip1KeyTyped(evt);
            }
        });

        maleEquip1Button.setText("Browse");
        maleEquip1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleEquip1ButtonActionPerformed(evt);
            }
        });

        jLabel24.setText("Female Model Equip 1");

        femaleEquip1.setText("-1");
        femaleEquip1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                femaleEquip1KeyTyped(evt);
            }
        });

        femaleEquip1Button.setText("Browse");
        femaleEquip1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleEquip1ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(invModel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invModelButton))
                    .addComponent(jLabel17)
                    .addComponent(invModelZoom, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(maleEquip1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maleEquip1Button))
                    .addComponent(jLabel24)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(femaleEquip1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(femaleEquip1Button)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(maleEquip2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maleEquip2Button))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(maleEquip3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(femaleEquip2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(femaleEquip2Button)
                            .addComponent(maleEquip3Button)))
                    .addComponent(jLabel21)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(femaleEquip3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(femaleEquip3Button)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invModelButton)
                    .addComponent(maleEquip2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maleEquip2Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invModelZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(femaleEquip2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(femaleEquip2Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maleEquip3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maleEquip3Button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(femaleEquip3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(femaleEquip3Button)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maleEquip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maleEquip1Button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(femaleEquip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(femaleEquip1Button))))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Model Options", jPanel3);

        jLabel10.setText("Team ID");

        teamID.setText("255");
        teamID.setToolTipText("Leave as is unless you know what you're doing.");
        teamID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teamIDKeyTyped(evt);
            }
        });

        stackable.setText("Stackable");

        jLabel11.setText("Stackable IDs");

        jLabel12.setText("Stackable Amounts");

        jLabel14.setText("Lended Item ID");

        lendItemID.setText("-1");
        lendItemID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lendItemIDKeyTyped(evt);
            }
        });

        switchLendItemID.setText("-1");
        switchLendItemID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                switchLendItemIDKeyTyped(evt);
            }
        });

        jLabel15.setText("Switch Lended Item ID");

        jLabel25.setText("Changed Model Colors");

        jLabel26.setText("Changed Texture Colors");

        jLabel27.setText("Weapon Type");

        weaponType.setText("-1");
        weaponType.setToolTipText("<html>\n<p>\n0 = Unarmed\n<br />\n1 = Special Bar\n<br />\n2 = Axe\n<br />\n6 = 1 Handed Sword\n<br />\n7 = 2 Handed Sword\n<br />\n8 = Mace\n<br />\n9 = Claws\n<br />\n14 = Spears\n<br />\n16 = Longbow\n</p>\n</html>");
        weaponType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                weaponTypeKeyTyped(evt);
            }
        });

        jLabel28.setText("Render Animation");

        renderAnimation.setText("-1");
        renderAnimation.setToolTipText("<html>\n<p>\n132 = 2 Handed Wield Animation\n<br />\n2583 = Claws Wield Animation\n<br />\n2554 = 1 Handed Sword Wield Animation\n<br />\n2052 = Katana Wield Animation\n</p>\n</html> ");
        renderAnimation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                renderAnimationKeyTyped(evt);
            }
        });

        jLabel30.setText("Model Offset 1");

        modelOffset1.setText("-1");
        modelOffset1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                modelOffset1KeyTyped(evt);
            }
        });

        jLabel31.setText("Model Offset 2");

        modelOffset2.setText("-1");
        modelOffset2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                modelOffset2KeyTyped(evt);
            }
        });

        jLabel32.setText("Model Rotation 1");

        modelRotation1.setText("-1");
        modelRotation1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                modelRotation1KeyTyped(evt);
            }
        });

        jLabel33.setText("Model Rotation 2");

        modelRotation2.setText("-1");
        modelRotation2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                modelRotation2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(teamID, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stackable))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(stackIDs, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stackAmts, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(switchLendItemID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addComponent(lendItemID, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(changedTextureColors, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(changedModelColors, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel26)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(modelOffset1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(modelOffset2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27)
                            .addComponent(weaponType, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(renderAnimation, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(modelRotation1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addComponent(modelRotation2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stackIDs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lendItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stackable)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stackAmts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(switchLendItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changedModelColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weaponType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changedTextureColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(renderAnimation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelOffset1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelOffset2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelRotation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelRotation2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Misc Options", jPanel4);

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Output", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backToMainButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(packButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backToMainButton)
                    .addComponent(packButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToMainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMainButtonActionPerformed
        setVisible(false);
        new Main().setVisible(true);
    }//GEN-LAST:event_backToMainButtonActionPerformed

    private void itemIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemIDKeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_itemIDKeyTyped

    private void packButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packButtonActionPerformed
        ItemPack.setSettings(this);
        ItemPack.proceedPacking();
    }//GEN-LAST:event_packButtonActionPerformed

    private void itemValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemValueKeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_itemValueKeyTyped

    private void equipTypeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_equipTypeKeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_equipTypeKeyTyped

    private void copyItemIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_copyItemIDKeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_copyItemIDKeyTyped

    private void notedItemIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_notedItemIDKeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_notedItemIDKeyTyped

    private void invModelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_invModelKeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_invModelKeyTyped

    private void invModelZoomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_invModelZoomKeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_invModelZoomKeyTyped

    private void maleEquip1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maleEquip1KeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_maleEquip1KeyTyped

    private void femaleEquip1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_femaleEquip1KeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_femaleEquip1KeyTyped

    private void maleEquip2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maleEquip2KeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_maleEquip2KeyTyped

    private void femaleEquip2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_femaleEquip2KeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_femaleEquip2KeyTyped

    private void maleEquip3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maleEquip3KeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_maleEquip3KeyTyped

    private void femaleEquip3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_femaleEquip3KeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_femaleEquip3KeyTyped

    private void teamIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teamIDKeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_teamIDKeyTyped

    private void lendItemIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lendItemIDKeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_lendItemIDKeyTyped

    private void switchLendItemIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_switchLendItemIDKeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_switchLendItemIDKeyTyped

    private void weaponTypeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weaponTypeKeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_weaponTypeKeyTyped

    private void renderAnimationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_renderAnimationKeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_renderAnimationKeyTyped

    private void modelOffset1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modelOffset1KeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_modelOffset1KeyTyped

    private void modelOffset2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modelOffset2KeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_modelOffset2KeyTyped

    private void modelRotation1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modelRotation1KeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_modelRotation1KeyTyped

    private void modelRotation2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modelRotation2KeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_modelRotation2KeyTyped

    private void invModelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invModelButtonActionPerformed
        Store cache = null;
        try {
            cache = new Store(currentCacheLocation);
        } catch (Exception e) {
            System.out.println("Unable to find the Current Cache Location.");
        }
        final JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setCurrentDirectory(getDirectory());
        if (evt.getSource() == invModelButton) {
            int returnVal = fc.showOpenDialog(ItemUI.this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                try {
                    invModel.setText(""+Utils.packCustomModel(cache, Utils.getBytesFromFile(new File(file.getPath()))));
                } catch (IOException ex) {
                    System.out.println("Error Packing Custom Model.");
                }
                setDirectory(new File(file.getPath()));
            }
        }
    }//GEN-LAST:event_invModelButtonActionPerformed

    private void maleEquip1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleEquip1ButtonActionPerformed
        Store cache = null;
        try {
            cache = new Store(currentCacheLocation);
        } catch (Exception e) {
            System.out.println("Unable to find the Current Cache Location.");
        }
        final JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setCurrentDirectory(getDirectory());
        if (evt.getSource() == maleEquip1Button) {
            int returnVal = fc.showOpenDialog(ItemUI.this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                try {
                    maleEquip1.setText(""+Utils.packCustomModel(cache, Utils.getBytesFromFile(new File(file.getPath()))));
                } catch (IOException ex) {
                    System.out.println("Error Packing Custom Model.");
                }
                setDirectory(new File(file.getPath()));
            }
        }
    }//GEN-LAST:event_maleEquip1ButtonActionPerformed

    private void femaleEquip1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleEquip1ButtonActionPerformed
        Store cache = null;
        try {
            cache = new Store(currentCacheLocation);
        } catch (Exception e) {
            System.out.println("Unable to find the Current Cache Location.");
        }
        final JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setCurrentDirectory(getDirectory());
        if (evt.getSource() == femaleEquip1Button) {
            int returnVal = fc.showOpenDialog(ItemUI.this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                try {
                    femaleEquip1.setText(""+Utils.packCustomModel(cache, Utils.getBytesFromFile(new File(file.getPath()))));
                } catch (IOException ex) {
                    System.out.println("Error Packing Custom Model.");
                }
                setDirectory(new File(file.getPath()));
            }
        }
    }//GEN-LAST:event_femaleEquip1ButtonActionPerformed

    private void maleEquip2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleEquip2ButtonActionPerformed
        Store cache = null;
        try {
            cache = new Store(currentCacheLocation);
        } catch (Exception e) {
            System.out.println("Unable to find the Current Cache Location.");
        }
        final JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setCurrentDirectory(getDirectory());
        if (evt.getSource() == maleEquip2Button) {
            int returnVal = fc.showOpenDialog(ItemUI.this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                try {
                    maleEquip2.setText(""+Utils.packCustomModel(cache, Utils.getBytesFromFile(new File(file.getPath()))));
                } catch (IOException ex) {
                    System.out.println("Error Packing Custom Model.");
                }
                setDirectory(new File(file.getPath()));
            }
        }
    }//GEN-LAST:event_maleEquip2ButtonActionPerformed

    private void femaleEquip2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleEquip2ButtonActionPerformed
        Store cache = null;
        try {
            cache = new Store(currentCacheLocation);
        } catch (Exception e) {
            System.out.println("Unable to find the Current Cache Location.");
        }
        final JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setCurrentDirectory(getDirectory());
        if (evt.getSource() == femaleEquip2Button) {
            int returnVal = fc.showOpenDialog(ItemUI.this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                try {
                    femaleEquip2.setText(""+Utils.packCustomModel(cache, Utils.getBytesFromFile(new File(file.getPath()))));
                } catch (IOException ex) {
                    System.out.println("Error Packing Custom Model.");
                }
                setDirectory(new File(file.getPath()));
            }
        }
    }//GEN-LAST:event_femaleEquip2ButtonActionPerformed

    private void maleEquip3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleEquip3ButtonActionPerformed
        Store cache = null;
        try {
            cache = new Store(currentCacheLocation);
        } catch (Exception e) {
            System.out.println("Unable to find the Current Cache Location.");
        }
        final JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setCurrentDirectory(getDirectory());
        if (evt.getSource() == maleEquip3Button) {
            int returnVal = fc.showOpenDialog(ItemUI.this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                try {
                    maleEquip3.setText(""+Utils.packCustomModel(cache, Utils.getBytesFromFile(new File(file.getPath()))));
                } catch (IOException ex) {
                    System.out.println("Error Packing Custom Model.");
                }
                setDirectory(new File(file.getPath()));
            }
        }
    }//GEN-LAST:event_maleEquip3ButtonActionPerformed

    private void femaleEquip3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleEquip3ButtonActionPerformed
        Store cache = null;
        try {
            cache = new Store(currentCacheLocation);
        } catch (Exception e) {
            System.out.println("Unable to find the Current Cache Location.");
        }
        final JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setCurrentDirectory(getDirectory());
        if (evt.getSource() == femaleEquip3Button) {
            int returnVal = fc.showOpenDialog(ItemUI.this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                try {
                    femaleEquip3.setText(""+Utils.packCustomModel(cache, Utils.getBytesFromFile(new File(file.getPath()))));
                } catch (IOException ex) {
                    System.out.println("Error Packing Custom Model.");
                }
                setDirectory(new File(file.getPath()));
            }
        }
    }//GEN-LAST:event_femaleEquip3ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMainButton;
    private javax.swing.JTextField changedModelColors;
    private javax.swing.JTextField changedTextureColors;
    private javax.swing.JTextField copyItemID;
    private javax.swing.JComboBox equipSlot;
    private javax.swing.JTextField equipType;
    private javax.swing.JTextField femaleEquip1;
    private javax.swing.JButton femaleEquip1Button;
    private javax.swing.JTextField femaleEquip2;
    private javax.swing.JButton femaleEquip2Button;
    private javax.swing.JTextField femaleEquip3;
    private javax.swing.JButton femaleEquip3Button;
    private javax.swing.JTextField ground0;
    private javax.swing.JTextField ground1;
    private javax.swing.JTextField ground2;
    private javax.swing.JTextField ground3;
    private javax.swing.JTextField ground4;
    private javax.swing.JTextField inv0;
    private javax.swing.JTextField inv1;
    private javax.swing.JTextField inv2;
    private javax.swing.JTextField inv3;
    private javax.swing.JTextField inv4;
    private javax.swing.JTextField invModel;
    private javax.swing.JButton invModelButton;
    private javax.swing.JTextField invModelZoom;
    private javax.swing.JTextField itemID;
    private javax.swing.JTextField itemName;
    private javax.swing.JTextField itemValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lendItemID;
    private javax.swing.JTextField maleEquip1;
    private javax.swing.JButton maleEquip1Button;
    private javax.swing.JTextField maleEquip2;
    private javax.swing.JButton maleEquip2Button;
    private javax.swing.JTextField maleEquip3;
    private javax.swing.JButton maleEquip3Button;
    private javax.swing.JCheckBox membersOnly;
    private javax.swing.JTextField modelOffset1;
    private javax.swing.JTextField modelOffset2;
    private javax.swing.JTextField modelRotation1;
    private javax.swing.JTextField modelRotation2;
    private javax.swing.JTextField notedItemID;
    private javax.swing.JTextArea output;
    private javax.swing.JButton packButton;
    private javax.swing.JTextField renderAnimation;
    private javax.swing.JTextField stackAmts;
    private javax.swing.JTextField stackIDs;
    private javax.swing.JCheckBox stackable;
    private javax.swing.JTextField switchLendItemID;
    private javax.swing.JTextField teamID;
    private javax.swing.JTextField weaponType;
    // End of variables declaration//GEN-END:variables
    final JFileChooser fc = new JFileChooser();
    File directory = new File("Desktop");

    public File getDirectory() {
        return directory;
    }

    public void setDirectory(File directory) {
        this.directory = directory;
    }
    
    private static String currentCacheLocation;

    public static String getCurrentCacheLocation() {
        return currentCacheLocation;
    }

    public static String currentCacheLocation(Main main) {
        return main.getCurrentCacheLocation().getText();
    }
    
    public static void setLocations(Main main) {
        currentCacheLocation = currentCacheLocation(main);
    }
    
    private void updateTextArea(final String text) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                output.append(text);
            }
        });
    }

    private void redirectSystemStreams() {
        OutputStream out = new OutputStream() {
            @Override
            public void write(int b) throws IOException {
                updateTextArea(String.valueOf((char) b));
            }

            @Override
            public void write(byte[] b, int off, int len) throws IOException {
                updateTextArea(new String(b, off, len));
            }

            @Override
            public void write(byte[] b) throws IOException {
                write(b, 0, b.length);
            }
        };

        System.setOut(new PrintStream(out, true));
        System.setErr(new PrintStream(out, true));
    }

    public JButton getBackToMainButton() {
        return backToMainButton;
    }

    public JTextField getChangedModelColors() {
        return changedModelColors;
    }

    public JTextField getChangedTextureColors() {
        return changedTextureColors;
    }

    public JTextField getCopyItemID() {
        return copyItemID;
    }

    public JComboBox getEquipSlot() {
        return equipSlot;
    }

    public JTextField getEquipType() {
        return equipType;
    }

    public JTextField getFemaleEquip1() {
        return femaleEquip1;
    }

    public JTextField getFemaleEquip2() {
        return femaleEquip2;
    }

    public JTextField getFemaleEquip3() {
        return femaleEquip3;
    }

    public JTextField getGround0() {
        return ground0;
    }

    public JTextField getGround1() {
        return ground1;
    }

    public JTextField getGround2() {
        return ground2;
    }

    public JTextField getGround3() {
        return ground3;
    }

    public JTextField getGround4() {
        return ground4;
    }

    public JTextField getInv0() {
        return inv0;
    }

    public JTextField getInv1() {
        return inv1;
    }

    public JTextField getInv2() {
        return inv2;
    }

    public JTextField getInv3() {
        return inv3;
    }

    public JTextField getInv4() {
        return inv4;
    }

    public JTextField getInvModel() {
        return invModel;
    }

    public JTextField getInvModelZoom() {
        return invModelZoom;
    }

    public JTextField getItemID() {
        return itemID;
    }

    public JTextField getItemName() {
        return itemName;
    }

    public JTextField getItemValue() {
        return itemValue;
    }

    public JTextField getLendItemID() {
        return lendItemID;
    }

    public JTextField getMaleEquip1() {
        return maleEquip1;
    }

    public JTextField getMaleEquip2() {
        return maleEquip2;
    }

    public JTextField getMaleEquip3() {
        return maleEquip3;
    }

    public JCheckBox getMembersOnly() {
        return membersOnly;
    }

    public JTextField getNotedItemID() {
        return notedItemID;
    }

    public JTextField getRenderAnimation() {
        return renderAnimation;
    }

    public JTextField getStackAmts() {
        return stackAmts;
    }

    public JTextField getStackIDs() {
        return stackIDs;
    }

    public JCheckBox getStackable() {
        return stackable;
    }

    public JTextField getSwitchLendItemID() {
        return switchLendItemID;
    }

    public JTextField getTeamID() {
        return teamID;
    }

    public JTextField getWeaponType() {
        return weaponType;
    }

    public JTextField getModelOffset1() {
        return modelOffset1;
    }

    public JTextField getModelOffset2() {
        return modelOffset2;
    }

    public JTextField getModelRotation1() {
        return modelRotation1;
    }

    public JTextField getModelRotation2() {
        return modelRotation2;
    }
}
