/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cc;

import com.cc.ui.ItemUI;
import com.cc.ui.NPCUI;
import com.cc.ui.NormalUI;
import com.cc.ui.ObjectUI;
import java.io.File;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JTextField;

/**
 *
 * @author travis
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        setTitle("Somethin Catchy Cache Packer");
        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        actionBox = new javax.swing.JComboBox();
        sumbitButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        currentCacheLocation = new javax.swing.JTextField();
        currentCacheButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        newCacheLocation = new javax.swing.JTextField();
        newCacheButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        xteasLocation = new javax.swing.JTextField();
        xteasButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cc/somethin-catchy.png"))); // NOI18N

        jLabel2.setText("Version 2.0");

        jLabel3.setText("What would you like to do?");

        actionBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal Cache Packing", "Custom Item Packing", "Custom NPC Packing", "Custom Object Packing", "Custom Sprite Packing" }));

        sumbitButton.setText("Let's Do It!");
        sumbitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumbitButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Set Your Current Cache Location");

        currentCacheLocation.setText("./PackTo/");

        currentCacheButton.setText("Browse");
        currentCacheButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentCacheButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Set The New Cache Location");

        newCacheLocation.setText("./PackFrom/  (If Applicable)");

        newCacheButton.setText("Browse");
        newCacheButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCacheButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Set The UnPacked Xteas Location");

        xteasLocation.setText("./unpackedXteas/ (If Applicable)");

        xteasButton.setText("Browse");
        xteasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xteasButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Designed and Programmed by Frosty @ Cloud-Code.com");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(actionBox, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(newCacheLocation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(currentCacheLocation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(currentCacheButton)
                                    .addComponent(newCacheButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(xteasLocation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xteasButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(sumbitButton)))
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(actionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentCacheLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentCacheButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCacheLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCacheButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xteasLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xteasButton))
                .addGap(42, 42, 42)
                .addComponent(sumbitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sumbitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumbitButtonActionPerformed
        setVisible(false);
        if (actionBox.getSelectedIndex() == 0) {
            NormalUI.setLocations(this);
            new NormalUI().setVisible(true);
        } else if (actionBox.getSelectedIndex() == 1) {
            ItemUI.setLocations(this);
            new ItemUI().setVisible(true);
        } else if (actionBox.getSelectedIndex() == 2) {
            NPCUI.setLocations(this);
            new NPCUI().setVisible(true);
        } else if (actionBox.getSelectedIndex() == 3) {
           ObjectUI.setLocations(this);
           new ObjectUI().setVisible(true);
           
        } else
            setVisible(true);
    }//GEN-LAST:event_sumbitButtonActionPerformed

    private void currentCacheButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentCacheButtonActionPerformed
            final JFileChooser fc = new JFileChooser();
            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            fc.setCurrentDirectory(getDirectory());
            if (evt.getSource() == currentCacheButton) {
                int returnVal = fc.showOpenDialog(Main.this);

                if (returnVal == JFileChooser.APPROVE_OPTION) {
                    File file = fc.getSelectedFile();
                    currentCacheLocation.setText(file.getPath()+"/");
                    setDirectory(new File(file.getPath()));
                }
             }
    }//GEN-LAST:event_currentCacheButtonActionPerformed

    private void newCacheButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCacheButtonActionPerformed
            final JFileChooser fc = new JFileChooser();
            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            fc.setCurrentDirectory(getDirectory());
            if (evt.getSource() == newCacheButton) {
                int returnVal = fc.showOpenDialog(Main.this);

                if (returnVal == JFileChooser.APPROVE_OPTION) {
                    File file = fc.getSelectedFile();
                    newCacheLocation.setText(file.getPath()+"/");
                    setDirectory(new File(file.getPath()));
                }
             }
    }//GEN-LAST:event_newCacheButtonActionPerformed

    private void xteasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xteasButtonActionPerformed
            final JFileChooser fc = new JFileChooser();
            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            fc.setCurrentDirectory(getDirectory());
            if (evt.getSource() == xteasButton) {
                int returnVal = fc.showOpenDialog(Main.this);

                if (returnVal == JFileChooser.APPROVE_OPTION) {
                    File file = fc.getSelectedFile();
                    xteasLocation.setText(file.getPath()+"/");
                    setDirectory(new File(file.getPath()));
                }
             }
    }//GEN-LAST:event_xteasButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox actionBox;
    private javax.swing.JButton currentCacheButton;
    private javax.swing.JTextField currentCacheLocation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton newCacheButton;
    private javax.swing.JTextField newCacheLocation;
    private javax.swing.JButton sumbitButton;
    private javax.swing.JButton xteasButton;
    private javax.swing.JTextField xteasLocation;
    // End of variables declaration//GEN-END:variables

    public JTextField getCurrentCacheLocation() {
        return currentCacheLocation;
    }
    
    public JTextField getNewCacheLocation() {
        return newCacheLocation;
    }
        
    public JTextField getxTeasLocation() {
        return xteasLocation;
    }
    
    final JFileChooser fc = new JFileChooser();
    File directory = new File("Desktop");

    public File getDirectory() {
        return directory;
    }

    public void setDirectory(File directory) {
        this.directory = directory;
    }
}
